package com.nahupay.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;

/**
 * A NahuPay payment object.
 *
 * <p>Returned by {@code PaymentsResource.create()}, {@code retrieve()},
 * {@code list()}, {@code cancel()}, etc.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Payment {

    @JsonProperty("id")             public String id;
    @JsonProperty("reference")      public String reference;
    @JsonProperty("amount")         public BigDecimal amount;
    @JsonProperty("currency")       public String currency;
    @JsonProperty("status")         public String status;
    @JsonProperty("mode")           public String mode;
    @JsonProperty("customerEmail")  public String customerEmail;
    @JsonProperty("customerName")   public String customerName;
    @JsonProperty("customerPhone")  public String customerPhone;
    @JsonProperty("description")    public String description;

    /**
     * Internal provider-callback URL (generated by NahuPay).
     * Not the merchant's webhook endpoint — see {@link #webhookUrl}.
     */
    @JsonProperty("callbackUrl")    public String callbackUrl;
    @JsonProperty("returnUrl")      public String returnUrl;

    /** Merchant's server-side webhook endpoint. */
    @JsonProperty("webhookUrl")     public String webhookUrl;

    /** Full URL of the hosted checkout page. Redirect the customer here. */
    @JsonProperty("checkoutUrl")    public String checkoutUrl;

    /** Raw metadata string. Use {@code new ObjectMapper().readValue(metadata, ...)} to parse. */
    @JsonProperty("metadata")       public String metadata;

    @JsonProperty("paymentMethod")  public String paymentMethod;
    @JsonProperty("cardLast4")      public String cardLast4;
    @JsonProperty("cardBrand")      public String cardBrand;
    @JsonProperty("failureReason")  public String failureReason;
    @JsonProperty("expiresAt")      public String expiresAt;
    @JsonProperty("paidAt")         public String paidAt;
    @JsonProperty("createdAt")      public String createdAt;

    @Override
    public String toString() {
        return "Payment{reference='" + reference + "', amount=" + amount
                + ", status='" + status + "', mode='" + mode + "'}";
    }
}
